verbose = "info"
no_progress = true
cache = true
max_cache_age = "1d"
max_redirects = 10
max_retries = 2
max_concurrency = 8
timeout = 30
retry_wait_time = 2
accept = ["200..=299", "429"]
include_fragments = "full"
exclude_all_private = true
exclude = [
  '^https://www\.figma\.com/',
  '^https://disk\.yandex\.ru/'
]
exclude_path = [
  "frontend/prototype/package-lock.json",
  "frontend/faceguard-web/package-lock.json"
]
